import { Metadata } from "next";
import Section1 from "./_components/Section1";
import DrivesSection from "./_components/DriveSection";
import OurMission from "./_components/OurMission";
import Timeline from "./_components/TImeLine";
import OurTeam from "./_components/TeamMembers";
import Banner from "./_components/Banner";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Section1 />
      <DrivesSection />
      <OurMission />
      <Timeline />
      <OurTeam />
      <Banner />
    </>
  );
};

export default page;
