import React from "react";
import PricingSection from "./_components/Pricing";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Pricing",
  description: "Generated by create next app",
};
const page = () => {
  return <PricingSection />;
};

export default page;
