import { Metadata } from "next";
import Link from "next/link";
import Button from "./_components/Button";
export const metadata: Metadata = {
  title: "Not Found",
  description: "Generated by create next app",
};
export default function NotFound() {
  return (
    <main
      data-page="not-found"
      className="relative isolate min-h-screen overflow-hidden"
    >
      <div className="mx-auto flex min-h-screen w-full max-w-[900px] flex-col items-center justify-center px-6 text-center">
        <div className="bg-blue bg-clip-text text-[120px] font-extrabold leading-none tracking-tight text-transparent md:text-[160px]">
          404
        </div>

        <h1 className="mt-4 text-2xl md:text-3xl font-semibold text-white">
          Page Not Found
        </h1>
        <p className="mt-3 max-w-[560px] text-sm md:text-base text-white/70">
          The page you’re looking for can’t be found. Double‑check the URL and
          try again. Or click the button below.
        </p>
        <div
          className="absolute top-10 -z-10 left-50 w-[950px] h-[950px] rounded-full 
                bg-[radial-gradient(circle,rgba(0,102,255,0.4)_0%,rgba(0,0,64,0)_70%)]
                blur-3xl pointer-events-none"
        ></div>
        <div className="mt-8 flex flex-col md:flex-row  items-center gap-3">
          <Button content="View Pricing" isBlue={true} urlPath="/pricing" />
          <Button content="Go Home" isBlue={false} urlPath="/" />
        </div>
      </div>
    </main>
  );
}
