import React from "react";
import ContactSection from "./_components/ContactSection";
import FaqSection from "./_components/FAQSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <ContactSection />
      <FaqSection />
    </div>
  );
};

export default page;
