import React from "react";
import Section1 from "./_components/Section1";
import Banner from "./_components/Banner";
import PortfolioView from "./_components/PortfolioView";
import RewardSection from "./_components/RewardSection";
import RewardSection2 from "./_components/RewardSection2";
import ExploreSection from "./_components/ExploreSection";
import TestimonialCarousel from "./_components/TestimonialCarousel";
import GetStarted from "./_components/GetStarted";
import AllArticals from "./_components/AllArticals";
import DownloadDetails from "./_components/DownloadDetail";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Section1 />
      <Banner />
      <PortfolioView />
      <RewardSection />
      <RewardSection2 />
      <ExploreSection />
      <TestimonialCarousel />
      <GetStarted />
      <AllArticals />
      <DownloadDetails />
    </div>
  );
};

export default page;
