import { Metadata } from "next";
import React from "react";
import TokensTable from "./_components/DataTables";
export const metadata: Metadata = {
  title: "Tokens",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="container mx-auto py-10">
      <TokensTable />
    </div>
  );
};

export default page;
