import React from "react";
import BlogFeatureSection from "./_components/BlogFeatureSection";
import NewsletterBanner from "./_components/NewsLetterBanner";
import LatestPosts from "./_components/LatestPosts";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <BlogFeatureSection />
      <NewsletterBanner />
      <LatestPosts />
    </>
  );
};

export default page;
